package model;
// Generated Mar 8, 2015 6:53:51 PM by Hibernate Tools 4.3.1

import java.io.Serializable;
import java.util.Date;

/**
 * Book generated by hbm2java
 */
public class Book implements Serializable {

    private String bookId;
    private String bookName;
    private Date bookDate;
    private String bookInformation;
    private String dateString;

    public Book() {
    }

    public Book(String bookId, String bookName, Date bookDate, String bookInformation, String dateString) {
        this.bookId = bookId;
        this.bookName = bookName;
        this.bookDate = bookDate;
        this.bookInformation = bookInformation;
        this.dateString = dateString;
    }

    public String getBookId() {
        return this.bookId;
    }

    public void setBookId(String bookId) {
        this.bookId = bookId;
    }

    public String getBookName() {
        return this.bookName;
    }

    public void setBookName(String bookName) {
        this.bookName = bookName;
    }

    public Date getBookDate() {
        return this.bookDate;
    }

    public void setBookDate(Date bookDate) {
        this.bookDate = bookDate;
    }

    public String getBookInformation() {
        return this.bookInformation;
    }

    public void setBookInformation(String bookInformation) {
        this.bookInformation = bookInformation;
    }

    public String getDateString() {
        return dateString;
    }

    public void setDateString(String dateString) {
        this.dateString = dateString;
    }

}
