package model;
// Generated Mar 8, 2015 6:53:51 PM by Hibernate Tools 4.3.1

import java.io.Serializable;

/**
 * Guest generated by hbm2java
 */
public class Guest implements Serializable {

    private String guestId;
    private String guestName;
    private String guestSex;
    private String guestJob;
    private String guestPhone;
    private String guestAddress;
    private String guestFoto;
    private String guestPresence;
    private String loginName;
    //view one to many
    private String bookId;

    public Guest() {
    }

    public Guest(String guestId, String guestName, String guestSex, String guestJob, String guestPhone, String guestAddress, String guestFoto, String guestPresence, String loginName) {
        this.guestId = guestId;
        this.guestName = guestName;
        this.guestSex = guestSex;
        this.guestJob = guestJob;
        this.guestPhone = guestPhone;
        this.guestAddress = guestAddress;
        this.guestFoto = guestFoto;
        this.guestPresence = guestPresence;
        this.loginName = loginName;
    }

    public String getGuestId() {
        return this.guestId;
    }

    public void setGuestId(String guestId) {
        this.guestId = guestId;
    }

    public String getGuestName() {
        return this.guestName;
    }

    public void setGuestName(String guestName) {
        this.guestName = guestName;
    }

    public String getGuestSex() {
        return this.guestSex;
    }

    public void setGuestSex(String guestSex) {
        this.guestSex = guestSex;
    }

    public String getGuestJob() {
        return this.guestJob;
    }

    public void setGuestJob(String guestJob) {
        this.guestJob = guestJob;
    }

    public String getGuestPhone() {
        return this.guestPhone;
    }

    public void setGuestPhone(String guestPhone) {
        this.guestPhone = guestPhone;
    }

    public String getGuestAddress() {
        return this.guestAddress;
    }

    public void setGuestAddress(String guestAddress) {
        this.guestAddress = guestAddress;
    }

    public String getGuestFoto() {
        return this.guestFoto;
    }

    public void setGuestFoto(String guestFoto) {
        this.guestFoto = guestFoto;
    }

    public String getGuestPresence() {
        return this.guestPresence;
    }

    public void setGuestPresence(String guestPresence) {
        this.guestPresence = guestPresence;
    }

    public String getLoginName() {
        return this.loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public String getBookId() {
        return this.bookId;
    }

    public void setBookId(String bookId) {
        this.bookId = bookId;
    }

}
